######################################################################
# vim: noet
#
# Makefile for the rtx kernel
#

TOP_DIR := ..

LOCAL_CFLAGS = -g -pg # -DDEBUG_KERN
LOCAL_LDFLAGS = -g -pg

REQ_LIBS = 
APPDEPS = cci 

include $(TOP_DIR)/make/rules.mk
