######################################################################
# vim: noet
#
# Makefile for the rtx kernel
#

TOP_DIR := ..

APP = kern

LOCAL_CFLAGS = -g -pg
LOCAL_LDFLAGS = -g -pg

include $(TOP_DIR)/make/rules.mk
