######################################################################
# vim: noet
#
# Makefile for the rtx kernel
#

TOP_DIR := ..

LOCAL_CFLAGS = -g
LOCAL_LDFLAGS = -g

REQ_LIBS = 
APPDEPS = cci rtx_util

include $(TOP_DIR)/make/rules.mk
