######################################################################
# vim: noet
#
# Makefile for the rtx kernel
#

TOP_DIR := ..


LOCAL_CFLAGS = -g -pg
LOCAL_LDFLAGS = -g -pg

REQ_LIBS =
APPDEPS =

include $(TOP_DIR)/make/rules.mk
