######################################################################
# vim: noet
#
# Makefile for the rtx kernel
#

TOP_DIR := ..

LOCAL_CFLAGS = -g #-DDEBUG_KERN
LOCAL_LDFLAGS = -g

REQ_LIBS = 
APPDEPS = cci wallclock keyboard crt abc rtx_util

include $(TOP_DIR)/make/rules.mk
